const APP_CHOOSE_TYPE = "APP_CHOOSE_TYPE";

const LOGIN = "LOGIN";
const CREATE_USER = "CREATE_USER";
const UPDATE_USER = "UPDATE_SERVICIO";

const GET_SERVICIOS = "GET_SERVICIOS";
const UPDATE_SERVICIO = "UPDATE_SERVICIO";
const DELETE_SERVICIO = "DELETE_SERVICIO";
const CREATE_SERVICIO = "CREATE_SERVICIO";

const GET_TRABAJOS = "GET_TRABAJOS";
const UPDATE_TRABAJO = "UPDATE_TRABAJO";
const DELETE_TRABAJO = "DELETE_TRABAJO";
const CREATE_TRABAJO = "CREATE_TRABAJO";

const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

const LOAD_TOKEN_USER = "LOAD_TOKEN_USER";

export {
  LOGIN,
  CREATE_USER,
  UPDATE_USER,
  GET_SERVICIOS,
  UPDATE_SERVICIO,
  DELETE_SERVICIO,
  CREATE_SERVICIO,
  GET_TRABAJOS,
  UPDATE_TRABAJO,
  DELETE_TRABAJO,
  CREATE_TRABAJO,
  APP_CHOOSE_TYPE,
  FETCH_PRODUCTS_PENDING,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  LOAD_TOKEN_USER
};
