export const GET_CATEGORIAS = "GET_CATEGORIAS";
export const UPDATE_CATEGORIA = "UPDATE_CATEGORIA";
export const DELETE_CATEGORIA = "DELETE_CATEGORIA";
export const CREATE_CATEGORIA = "CREATE_CATEGORIA";
export const RESTORE_CATEGORIA = "RESTORE_CATEGORIA";
export const GET_CATEGORIAS_DELETED = "GET_CATEGORIAS_DELETED";
export const SELECT_CATEGORIA = "SELECT_CATEGORIA";
