export const GET_CLIENTES = "GET_CLIENTES";
export const UPDATE_CLIENTE = "UPDATE_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
export const CREATE_CLIENTE = "CREATE_CLIENTE";
export const RESTORE_CLIENTE = "RESTORE_CLIENTE";
export const GET_CLIENTES_DELETED = "GET_CLIENTES_DELETED";
export const SELECT_CLIENTE = "SELECT_CLIENTE";
