export const GET_EMPRESAS = "GET_EMPRESAS";
export const UPDATE_EMPRESA = "UPDATE_EMPRESA";
export const DELETE_EMPRESA = "DELETE_EMPRESA";
export const CREATE_EMPRESA = "CREATE_EMPRESA";
export const RESTORE_EMPRESA = "RESTORE_EMPRESA";
export const GET_EMPRESAS_DELETED = "GET_EMPRESAS_DELETED";
export const SELECT_EMPRESA = "SELECT_EMPRESA";
