export const GET_LOCALIDADES = "GET_LOCALIDADES";
export const UPDATE_LOCALIDAD = "UPDATE_LOCALIDAD";
export const DELETE_LOCALIDAD = "DELETE_LOCALIDAD";
export const CREATE_LOCALIDAD = "CREATE_LOCALIDAD";
export const RESTORE_LOCALIDAD = "RESTORE_LOCALIDAD";
export const GET_LOCALIDADES_DELETED = "GET_LOCALIDADES_DELETED";
export const SELECT_LOCALIDAD = "SELECT_LOCALIDAD";
