export const GET_SUBCATEGORIAS = "GET_SUBCATEGORIAS";
export const UPDATE_SUBCATEGORIA = "UPDATE_SUBCATEGORIA";
export const DELETE_SUBCATEGORIA = "DELETE_SUBCATEGORIA";
export const CREATE_SUBCATEGORIA = "CREATE_SUBCATEGORIA";
export const RESTORE_SUBCATEGORIA = "RESTORE_SUBCATEGORIA";
export const GET_SUBCATEGORIAS_DELETED = "GET_SUBCATEGORIAS_DELETED";
export const SELECT_SUBCATEGORIA = "SELECT_SUBCATEGORIA";
